"""
Local web server for the notes deskewer.

Run:  python server.py   (then open http://127.0.0.1:5000)

Nothing leaves your machine — PDFs are processed locally and cached in a
temp folder for the life of the process.
"""

from __future__ import annotations

import contextlib
import io
import json
import os
import re
import time
import traceback
import uuid
import tempfile
import atexit
import shutil
import zipfile
from datetime import datetime

import fitz  # PyMuPDF
from PIL import Image
from flask import Flask, request, jsonify, send_file, Response, abort
from werkzeug.exceptions import HTTPException

import imaging
import borders
import spellfix

app = Flask(__name__, static_folder="static", static_url_path="")

# Spelling-fix patches: id -> RGBA PIL image (the feathered word patch).
# Generated by /api/fix/generate, re-registered from their embedded PNGs when
# a draft reopens or an export body carries them — so a restarted server can
# always resolve every fix a client still references.
PATCHES: dict = {}


def _patch_image(pid: str):
    return PATCHES.get(pid)


imaging.set_patch_resolver(_patch_image)


def _register_fix(fx: dict) -> None:
    """Cache a fix dict's embedded base64 PNG under its id (idempotent)."""
    pid = str(fx.get("id", "") or "")
    if not pid or pid in PATCHES or not fx.get("png"):
        return
    try:
        import base64
        raw = base64.b64decode(fx["png"])
        PATCHES[pid] = Image.open(io.BytesIO(raw)).convert("RGBA")
    except Exception:
        pass


def _register_fixes_from_pages(pages: list) -> None:
    """Walk page-settings dicts (and their overlays) and cache every patch."""
    for ps in pages or []:
        if not isinstance(ps, dict):
            continue
        for fx in ps.get("fixes") or []:
            if isinstance(fx, dict):
                _register_fix(fx)
        for ov in ps.get("overlays") or []:
            if isinstance(ov, dict):
                for fx in ov.get("fixes") or []:
                    if isinstance(fx, dict):
                        _register_fix(fx)

PREVIEW_DPI = 110       # detection + on-screen preview
DEFAULT_EXPORT_DPI = 300

# Borders-tab board sentinel: export one PDF per board, zipped together.
ALL_BOARDS = "__all__"

# Board-wise previous-year-question PDFs, organised as
# PYQs/<BOARD>/<MEDIUM>/<SUBJECT>/<CHAPTER>/*.pdf
PYQS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "PYQs")
_SAFE_SEG = re.compile(r"^[A-Za-z0-9_-]+$")

FONTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")

# Saved drafts: every export snapshots the working PDFs + the full edit state
# (crops, angles, colours, watermark, borders, palette …) into
# drafts/<id>/, so any past export can be reopened and re-edited later.
DRAFTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "drafts")
_DRAFT_ID = re.compile(r"^[a-f0-9]{12}$")

# Python code is loaded once at start-up; if the files on disk are edited
# later, the running process silently keeps the old behaviour. The editor
# asks /api/borders/options on load, so we report staleness there and the
# UI shows a "restart the server" warning instead of exporting stale output.
_PROCESS_START = time.time()

WORK_DIR = tempfile.mkdtemp(prefix="notes_deskew_")
atexit.register(lambda: shutil.rmtree(WORK_DIR, ignore_errors=True))

# Crashes must leave a trace the user can send us: the terminal window is
# usually closed (or its scrollback gone) by the time anyone asks what went
# wrong, so every unhandled error is appended here, next to server.py.
LOG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "notes-editor.log")


def _log_exception(context: str):
    try:
        with open(LOG_PATH, "a", encoding="utf-8") as fh:
            fh.write(f"\n[{datetime.now():%Y-%m-%d %H:%M:%S}] {context}\n")
            fh.write(traceback.format_exc())
    except OSError:
        pass


@app.errorhandler(Exception)
def _api_error(e):
    """
    Every error leaves this server as JSON {"error": ...}. The editor shows
    that text in a toast; without this, an unhandled exception became a plain
    HTML 500 page the client could only render as a blank "export failed".
    """
    if isinstance(e, HTTPException):        # abort(...) keeps its status/text
        return jsonify({"error": e.description}), e.code
    _log_exception(f"{request.method} {request.path}")
    if isinstance(e, MemoryError):
        return jsonify({"error": "the computer ran out of memory during this "
                        "step — close other apps, or export at a lower DPI "
                        "(150 or 200) and try again"}), 500
    return jsonify({"error": f"{type(e).__name__}: {e} — full details were "
                    "saved to notes-editor.log (next to server.py)"}), 500

# job_id -> {"files": [ {fid, name, path, pages: [ {angle, crop, w, h} ] } ] }
JOBS: dict = {}
# (job_id, fid, page) -> deskew-DPI base raster (PIL RGB), before any rotation
BASE_CACHE: dict = {}

# Analysing a page (render + skew detect + margin scan) takes a moment, so a
# 40-page upload is a long silent wait. Requests that do it publish a live
# page counter here under a token the client makes up and sends along; the
# client polls /api/progress with that token and draws a real bar.
# token -> {done, total, label, ts}
PROGRESS: dict = {}
PROGRESS_TTL = 600.0        # forget tokens whose request died without cleanup


@contextlib.contextmanager
def _progress(token: str, total: int = 0, label: str = ""):
    """
    Publish page progress for one request under `token`, and always forget it
    when the request ends. Yields the dict to tick (None if the client sent no
    token, which every progress-aware helper treats as "don't report").
    """
    if not token:
        yield None
        return
    cutoff = time.time() - PROGRESS_TTL
    for stale in [t for t, p in PROGRESS.items() if p["ts"] < cutoff]:
        PROGRESS.pop(stale, None)
    prog = {"done": 0, "total": int(total), "label": label, "ts": time.time()}
    PROGRESS[token] = prog
    try:
        yield prog
    finally:
        PROGRESS.pop(token, None)


@app.route("/api/progress")
def progress():
    """
    Progress of a long request, by the token the client sent with it. An
    unknown token is a normal answer rather than an error — the request may
    not have reached the server yet, or may already be finishing up.
    """
    prog = PROGRESS.get((request.args.get("token") or "").strip())
    if prog is None:
        return jsonify({"unknown": True})
    return jsonify({"done": prog["done"], "total": prog["total"],
                    "label": prog["label"]})


def _page_count(path: str) -> int:
    with contextlib.closing(fitz.open(path)) as doc:
        return doc.page_count


def _job(job_id: str) -> dict:
    job = JOBS.get(job_id)
    if not job:
        # Restarting the app empties JOBS, but an already-open browser tab
        # still shows the pages it loaded earlier — tell them what happened.
        abort(410, "the app was restarted since these pages were loaded, so "
                   "this session is gone — reload the browser tab and add "
                   "the PDFs again")
    return job


def _find_file(job: dict, fid: str) -> dict:
    for f in job["files"]:
        if f["fid"] == fid:
            return f
    abort(404, "unknown file")


@app.route("/")
def index():
    return app.send_static_file("index.html")


def _analyse_pages(job_id: str, fid: str, path: str, start: int = 0,
                   prog: dict | None = None, label: str = "") -> list:
    """
    Auto-deskew + auto-margin pages [start:] of a working PDF and cache their
    base rasters. Returns the per-page dicts the editor works with.

    `prog` (from _progress) is ticked once per finished page, so a caller
    polling /api/progress sees the count climb through this loop.
    """
    doc = fitz.open(path)
    if prog is not None and label:
        prog["label"] = label
    pages = []
    for i in range(start, doc.page_count):
        base = imaging.render_page(doc, i, PREVIEW_DPI)
        angle = imaging.detect_skew(base)
        deskewed = imaging.deskew_image(base, angle)
        crop = imaging.content_bbox_fractions(deskewed)
        BASE_CACHE[(job_id, fid, i)] = base
        pages.append({
            "angle": angle,
            "crop": crop,
            "removals": [],
            "w": deskewed.width,
            "h": deskewed.height,
        })
        if prog is not None:
            prog["done"] += 1
            prog["ts"] = time.time()
    doc.close()
    return pages


def _append_uploads(job_id: str, f: dict, uploads: list,
                    prog: dict | None = None):
    """
    Merge uploaded PDFs onto the END of one working PDF, then analyse just the
    pages that appeared. The pages become part of that same document — they
    export inside the original PDF instead of as a separate file — and are
    editable like any other page.
    """
    doc = fitz.open(f["path"])
    start = doc.page_count
    names = []
    for up in uploads:
        blob = up.read()
        try:
            src = fitz.open(stream=blob, filetype="pdf")
        except Exception:
            doc.close()
            return jsonify({"error": f"{up.filename} is not a readable PDF"}), 400
        doc.insert_pdf(src)
        src.close()
        names.append(up.filename)
    added = doc.page_count - start
    tmp = f["path"] + ".tmp"
    doc.save(tmp)
    doc.close()
    os.replace(tmp, f["path"])

    if prog is not None:
        prog["total"] = added
    new_pages = _analyse_pages(job_id, f["fid"], f["path"], start,
                               prog=prog, label=f["name"])
    f["pages"].extend(new_pages)
    f["npages"] = len(f["pages"])
    return jsonify({"job": job_id, "appended": True, "fid": f["fid"],
                    "start": start, "npages": f["npages"],
                    "pages": new_pages, "sources": names})


@app.route("/api/upload", methods=["POST"])
def upload():
    uploads = [up for up in request.files.getlist("files")
               if (up.filename or "").lower().endswith(".pdf")]
    if not uploads:
        return jsonify({"error": "no PDF files"}), 400

    # "+ Add PDFs" sends the open job and the PDF being viewed: the new pages
    # are then merged onto the end of THAT document, so they stay one PDF and
    # still export as one file (not a zip of separate PDFs). An unknown or
    # expired job falls back to a fresh job — the client is told which
    # happened via "appended".
    job_id = (request.form.get("job") or "").strip()
    fid = (request.form.get("fid") or "").strip()
    token = (request.form.get("ptoken") or "").strip()

    with _progress(token, 0, f"Reading {len(uploads)} PDF(s)…") as prog:
        job = JOBS.get(job_id)
        if job and fid:
            target = next((f for f in job["files"] if f["fid"] == fid), None)
            if target is not None:
                return _append_uploads(job_id, target, uploads, prog)
        return _new_job(uploads, prog)


def _new_job(uploads: list, prog: dict | None = None):
    """
    Start a fresh job from uploaded PDFs. Every page count is read before any
    analysis, so a client polling progress gets a real denominator on its very
    first tick instead of watching the total grow file by file.
    """
    job_id = uuid.uuid4().hex[:12]
    job_dir = os.path.join(WORK_DIR, job_id)
    os.makedirs(job_dir, exist_ok=True)

    stored = []
    for up in uploads:
        fid = uuid.uuid4().hex[:8]
        path = os.path.join(job_dir, f"{fid}.pdf")
        up.save(path)
        try:
            npages = _page_count(path)
        except Exception:
            return jsonify({"error": f"{up.filename} is not a readable PDF"}), 400
        stored.append({"fid": fid, "name": up.filename, "path": path,
                       "npages": npages})

    if prog is not None:
        prog["total"] = sum(s["npages"] for s in stored)

    files = []
    for s in stored:
        pages = _analyse_pages(job_id, s["fid"], s["path"],
                               prog=prog, label=s["name"])
        files.append({**s, "npages": len(pages), "pages": pages})

    if not files:
        return jsonify({"error": "no valid PDFs"}), 400

    JOBS[job_id] = {"files": files, "dir": job_dir}

    # Strip server-only fields from the response.
    payload_files = [{
        "fid": f["fid"], "name": f["name"], "npages": f["npages"],
        "pages": f["pages"],
    } for f in files]
    return jsonify({"job": job_id, "files": payload_files, "appended": False})


def _color_from_args(args) -> dict:
    """Build a colour dict from flat query params (c* prefixed)."""
    return {
        "mode": args.get("cmode", "none"),
        "brightness": float(args.get("cbright", "1")),
        "contrast": float(args.get("ccontrast", "1")),
        "saturation": float(args.get("csat", "1")),
        "whiten": float(args.get("cwhiten", "0")),
        "deyellow": float(args.get("cdeyellow", "0")),
    }


def _crop_from_args(args):
    """Optional crop insets from query params (cr*); None if no crop."""
    c = {
        "left": float(args.get("crl", "0") or 0),
        "top": float(args.get("crt", "0") or 0),
        "right": float(args.get("crr", "0") or 0),
        "bottom": float(args.get("crb", "0") or 0),
    }
    return None if all(v <= 0 for v in c.values()) else c


def _persp_from_args(args):
    """
    Four-corner perspective quad from the compact query param (psp).

    Sent as eight comma-separated fractions — tl, tr, br, bl — because it rides
    on every preview and thumbnail URL. None means "leave the page flat".
    """
    raw = args.get("psp", "")
    if not raw:
        return None
    try:
        nums = [float(v) for v in raw.split(",")]
    except ValueError:
        return None
    return nums if len(nums) == 8 else None


def _overlays_from_args(args) -> list[dict]:
    """Parse merged-page overlays from query param (ov, JSON list)."""
    raw = args.get("ov", "")
    if not raw:
        return []
    try:
        data = json.loads(raw)
        return data if isinstance(data, list) else []
    except ValueError:
        return []


def _shapes_from_args(args) -> list[dict]:
    """Parse shape-filler polygons from query param (shp, JSON list)."""
    raw = args.get("shp", "")
    if not raw:
        return []
    try:
        data = json.loads(raw)
        return data if isinstance(data, list) else []
    except ValueError:
        return []


def _removals_from_args(args) -> list[dict]:
    """Parse removals from query param (rms)."""
    raw = args.get("rms", "")
    if not raw:
        return []
    import json
    try:
        if raw.startswith("["):
            return json.loads(raw)
        res = []
        for pair in raw.split("|"):
            parts = pair.split(",")
            if len(parts) == 2:
                res.append({"top": float(parts[0]), "bottom": float(parts[1])})
        return res
    except Exception:
        return []


def _fixes_from_args(args) -> list[dict]:
    """Parse spelling fixes from query param (fxs, JSON list of {id, rect})."""
    raw = args.get("fxs", "")
    if not raw:
        return []
    try:
        data = json.loads(raw)
        return data if isinstance(data, list) else []
    except ValueError:
        return []


@app.route("/api/preview")
def preview():
    """
    Deskewed (+ optional crop / removals / scan / colour) preview PNG for one page.
    Pass maxdim to get a small thumbnail (crop is applied when maxdim is set).
    """
    job_id = request.args.get("job", "")
    fid = request.args.get("fid", "")
    page = int(request.args.get("page", "0"))
    angle = float(request.args.get("angle", "0"))
    rot = float(request.args.get("rot", "0") or 0)
    maxdim = int(request.args.get("maxdim", "0"))
    color = _color_from_args(request.args)
    crop = _crop_from_args(request.args)
    removals = _removals_from_args(request.args)
    watermark = request.args.get("wm", "0") == "1"
    wm_opacity = float(request.args.get("wmop", "1") or 1)
    wm_scale = float(request.args.get("wmscale", "1") or 1)
    wm_rotate = float(request.args.get("wmrot", "0") or 0)
    wm_dx = float(request.args.get("wmdx", "0") or 0)
    wm_dy = float(request.args.get("wmdy", "0") or 0)
    # Where the watermark anchors: the margin box or the whole sheet. The page's
    # crop insets come in separately (w*) because the main preview shows the
    # *uncropped* page — it needs the margins for placement without cropping.
    wm_center_margins = request.args.get("wmcm", "0") == "1"
    wm_crop = {
        "left": float(request.args.get("wcl", "0") or 0),
        "top": float(request.args.get("wct", "0") or 0),
        "right": float(request.args.get("wcr", "0") or 0),
        "bottom": float(request.args.get("wcb", "0") or 0),
    }

    _job(job_id)
    base = BASE_CACHE.get((job_id, fid, page))
    if base is None:
        abort(404, "no cached page")

    # For thumbnails, downscale the source first so all pages render fast.
    src = base
    if 0 < maxdim < max(base.size):
        scale = maxdim / max(base.size)
        src = base.resize((max(1, int(base.width * scale)),
                           max(1, int(base.height * scale))), Image.BILINEAR)

    palette = _job(job_id).get("palette")
    out = imaging.deskew_image(imaging.rotate_page(src, rot), angle)
    # The perspective warp joins rotate/deskew as a geometry fix, before
    # anything measures the page. It keeps the sheet's size, so the crop guides
    # and gap bands drawn over this preview still mean what they did.
    out = imaging.apply_perspective(out, _persp_from_args(request.args))
    # Removals before crop: their fractions are in uncropped-deskewed space.
    if removals:
        out = imaging.apply_removals(out, removals)
    # Spelling fixes live in that same post-removals space, and go on before
    # the crop and colour so the mended ink is graded with the page.
    fixes = _fixes_from_args(request.args)
    if fixes:
        out = imaging.apply_fixes(out, fixes)
    # Content pulled from other pages is part of the page too: where it sits
    # past the margins the sheet grows to keep it instead of clipping it, so
    # every step from here on works against that grown box.
    overlays = _overlays_from_args(request.args)
    ecrop = imaging.expanded_crop(crop, overlays)
    if ecrop:
        out = imaging.apply_crop(out, ecrop)
    out = imaging.finish_color(out, color, palette)
    # Merged-page overlays sit under the watermark, exactly like on export.
    if overlays:
        out = imaging.paste_overlays(
            out, overlays, ecrop, palette,
            lambda ov: BASE_CACHE.get(
                (job_id, str(ov.get("fid", "")), int(ov.get("page", 0) or 0))))
    # Shape-filler polygons cover content under the watermark, like on export.
    shapes = _shapes_from_args(request.args)
    if shapes:
        out = imaging.draw_shapes(out, shapes, ecrop)
    if watermark:
        sheet, centre = imaging.watermark_geometry(
            out.size, ecrop if ecrop else wm_crop, wm_center_margins,
            cropped=ecrop is not None, margin_crop=wm_crop)
        out = imaging.apply_watermark(out, wm_opacity, wm_scale, wm_rotate,
                                      wm_dx, wm_dy, sheet, centre,
                                      align_ink=wm_center_margins)
    return Response(imaging.to_png_bytes(out), mimetype="image/png")


@app.route("/api/fix/generate", methods=["POST"])
def fix_generate():
    """
    Rewrite one misspelled word in the writer's own hand (via OpenAI).

    Body: { job, fid, page, rect: [x0,y0,x1,y1], correct, wrong?, n?,
            angle?, rotate?, persp?, removals? }
    `rect` is in fractions of the uncropped deskewed post-removals page —
    exactly what the user boxed on the main preview. The page is re-rendered
    at export DPI (300) so the word reaches the API at full detail, whatever
    the on-screen preview resolution.

    Returns { candidates: [ {id, rect, png, thumb} ] } — the client shows the
    thumbs, and the one the user picks is stored on the page as
    {id, rect, png} (the png rides along so drafts and exports survive a
    server restart).
    """
    data = request.get_json(force=True)
    job = _job(data.get("job", ""))
    f = _find_file(job, data.get("fid", ""))
    page = int(data.get("page", 0))
    rect = data.get("rect") or []
    correct = str(data.get("correct", "") or "").strip()
    wrong = str(data.get("wrong", "") or "").strip()
    n = int(data.get("n", 3) or 3)
    if len(rect) != 4:
        return jsonify({"error": "bad word box"}), 400
    if not correct:
        return jsonify({"error": "type the correct spelling first"}), 400
    if not spellfix.api_ready():
        return jsonify({"error": "OPENAI_API_KEY missing — put it in a .env "
                        "file next to server.py and restart"}), 400
    if not 0 <= page < _page_count(f["path"]):
        return jsonify({"error": "bad page"}), 400

    # Same geometry chain as export, at export DPI, stopping right where the
    # fix will later be composited (post-removals, pre-crop, raw colour).
    with contextlib.closing(fitz.open(f["path"])) as doc:
        hi = imaging.render_page(doc, page, DEFAULT_EXPORT_DPI)
    geo = imaging.apply_perspective(
        imaging.deskew_image(
            imaging.rotate_page(hi, float(data.get("rotate", 0) or 0)),
            float(data.get("angle", 0) or 0)),
        data.get("persp"))
    geo = imaging.apply_removals(geo, data.get("removals") or [])

    try:
        cands = spellfix.generate_candidates(geo, [float(v) for v in rect],
                                             wrong, correct, n)
    except (RuntimeError, ValueError) as e:
        return jsonify({"error": str(e)}), 502

    import base64
    out = []
    for c in cands:
        PATCHES[c["id"]] = Image.open(io.BytesIO(c["png"])).convert("RGBA")
        out.append({"id": c["id"], "rect": c["rect"],
                    "png": base64.b64encode(c["png"]).decode(),
                    "thumb": base64.b64encode(c["thumb"]).decode()})
    return jsonify({"candidates": out})


@app.route("/api/spellcheck", methods=["POST"])
def spellcheck():
    """
    Read pages with a vision model and list suspected spelling mistakes.

    Body: { job, ptoken?, pages: [ {fid, pi, src, angle?, rotate?, persp?,
            removals?} ] } — one entry per page to check, with that page's
    geometry so the returned x/y positions line up with the editor preview.
    Returns { findings: [ {fid, pi, wrong, correct, context, x, y} ],
              errors: [ {pi, error} ] }. Text only — no image generation.
    """
    data = request.get_json(force=True)
    job_id = data.get("job", "")
    job = _job(job_id)
    pages = [p for p in (data.get("pages") or []) if isinstance(p, dict)]
    if not pages:
        return jsonify({"error": "no pages to check"}), 400
    if not spellfix.api_ready():
        return jsonify({"error": "OPENAI_API_KEY missing — put it in a .env "
                        "file next to server.py and restart"}), 400

    def page_image(ps):
        fid = str(ps.get("fid", ""))
        src = int(ps.get("src", 0) or 0)
        base = BASE_CACHE.get((job_id, fid, src))
        if base is None:
            f = _find_file(job, fid)
            with contextlib.closing(fitz.open(f["path"])) as doc:
                base = imaging.render_page(doc, src, PREVIEW_DPI)
        # Same space as the main preview (uncropped, post-removals), so the
        # model's word positions can be marked straight onto it.
        geo = imaging.apply_perspective(
            imaging.deskew_image(
                imaging.rotate_page(base, float(ps.get("rotate", 0) or 0)),
                float(ps.get("angle", 0) or 0)),
            ps.get("persp"))
        geo = imaging.apply_removals(geo, ps.get("removals") or [])
        # Apply existing spelling fixes, so mended words don't get re-flagged.
        return imaging.apply_fixes(geo, ps.get("fixes") or [])

    token = (data.get("ptoken") or "").strip()
    findings, errors = [], []
    with _progress(token, len(pages), "Reading handwriting…") as prog:
        from concurrent.futures import ThreadPoolExecutor

        def work(ps):
            try:
                ms = spellfix.check_page(page_image(ps))
                return [{**m, "fid": str(ps.get("fid", "")),
                         "pi": int(ps.get("pi", 0) or 0)} for m in ms]
            except Exception as e:
                return {"pi": int(ps.get("pi", 0) or 0), "error": str(e)}

        with ThreadPoolExecutor(max_workers=4) as ex:
            for res in ex.map(work, pages):
                if prog is not None:
                    prog["done"] += 1
                if isinstance(res, dict):
                    errors.append(res)
                else:
                    findings.extend(res)
    findings.sort(key=lambda m: (m["fid"], m["pi"], m["y"]))
    return jsonify({"findings": findings, "errors": errors})


@app.route("/api/detect_gaps", methods=["POST", "GET"])
def detect_gaps():
    """Auto-detect blank vertical gaps for a given page."""
    req_json = request.get_json(silent=True) or {}
    job_id = (request.args.get("job") or "") or req_json.get("job", "")
    fid = (request.args.get("fid") or "") or req_json.get("fid", "")
    _page = request.args.get("page")
    page = int(_page) if _page is not None else int(req_json.get("page", 0))
    _angle = request.args.get("angle")
    angle = float(_angle) if _angle is not None else float(req_json.get("angle", 0))
    _rot = request.args.get("rot")
    rot = float(_rot) if _rot is not None else float(req_json.get("rotate", 0) or 0)
    crop = _crop_from_args(request.args) if request.args.get("crl") else req_json.get("crop")
    persp = _persp_from_args(request.args) if request.args.get("psp") \
        else req_json.get("persp")

    _job(job_id)
    base = BASE_CACHE.get((job_id, fid, page))
    if base is None:
        abort(404, "no cached page")

    deskewed = imaging.apply_perspective(
        imaging.deskew_image(imaging.rotate_page(base, rot), angle), persp)
    if crop:
        deskewed = imaging.apply_crop(deskewed, crop)

    gaps = imaging.auto_detect_blank_gaps(deskewed)
    if crop:
        # Detection ran on the cropped page (better signal — skips the header
        # and margins), but gap fractions are stored in uncropped-deskewed
        # space, so map them back through the crop insets.
        ct = float(crop.get("top", 0) or 0)
        cb = float(crop.get("bottom", 0) or 0)
        kh = max(1e-6, 1.0 - ct - cb)
        gaps = [{"top": round(ct + g["top"] * kh, 4),
                 "bottom": round(ct + g["bottom"] * kh, 4)} for g in gaps]
    return jsonify({"gaps": gaps})


@app.route("/api/sample", methods=["POST"])
def sample():
    """Learn a colour palette from an uploaded sample page (image or PDF)."""
    job_id = request.form.get("job", "")
    job = _job(job_id)
    up = request.files.get("file")
    if not up:
        return jsonify({"error": "no file"}), 400

    data = up.read()
    name = (up.filename or "").lower()
    if name.endswith(".pdf"):
        doc = fitz.open(stream=data, filetype="pdf")
        img = imaging.render_page(doc, 0, PREVIEW_DPI)
        doc.close()
    else:
        img = Image.open(io.BytesIO(data)).convert("RGB")

    palette = imaging.extract_palette(img)
    job["palette"] = palette
    return jsonify(palette)


# ---------------------------------------------------------------------------
# Export filenames
#
# Bordered exports are named "<BOARD>_<MEDIUM>_<SUBJECT>_CH<nn>-ChapterName.pdf"
# — e.g. MP_EN_PHY_CH01-ElectricCharges.pdf. The board code is derived from the
# cover's board name ("MP Board" -> MP); the medium (EN/HN) and subject
# (PHY/CHEM/BIO/…) codes come straight from the Borders tab.
# ---------------------------------------------------------------------------

_WORDS = re.compile(r"[^A-Za-z0-9]+")


def _code(value: str, limit: int = 12) -> str:
    """Squash a label into a filename-safe upper-case code."""
    return _WORDS.sub("", str(value or "")).upper()[:limit]


def _board_code(board: str) -> str:
    """'MP Board' -> 'MP'; 'UP' -> 'UP'."""
    words = [w for w in _WORDS.split(str(board or "")) if w]
    named = [w for w in words if w.lower() not in ("board", "boards")]
    return _code((named or words or [""])[0], 6)


def _camel(text: str) -> str:
    """'Electric charges' -> 'ElectricCharges' (chapter name in filenames)."""
    joined = "".join(w[:1].upper() + w[1:]
                     for w in _WORDS.split(str(text or "")) if w)
    return joined[:80]              # keep the whole name well inside 255 chars


def _chapter_tag(number: str, name: str) -> str:
    """'5', 'Electric charges' -> 'CH05-ElectricCharges'."""
    num = str(number or "").strip()
    parts = []
    if num:
        parts.append("CH" + (num.zfill(2) if num.isdigit() else _code(num, 6)))
    nm = _camel(name)
    if nm:
        parts.append(nm)
    return "-".join(parts)


def _coded_name(board: str, medium: str, subject: str, number: str, name: str,
                ext: str = ".pdf") -> str | None:
    """Coded filename, or None when no board/medium/subject code was picked."""
    codes = [c for c in (_board_code(board), _code(medium, 4),
                         _code(subject, 6)) if c]
    if not codes:
        return None
    tag = _chapter_tag(number, name)
    return "_".join(codes + ([tag] if tag else [])) + ext


def _export_name(orig_name: str, bordered: bool, number: str, name: str,
                 board: str = "", medium: str = "", subject: str = "") -> str:
    """
    Coded chapter filename (MP_EN_PHY_CH01-Name.pdf) once the Borders tab
    carries at least one of board/medium/subject; a readable
    "Chapter 05 - Name.pdf" when it only carries chapter info; else *_fixed.
    """
    stem = os.path.splitext(orig_name)[0]
    if bordered:
        coded = _coded_name(board, medium, subject, number, name)
        if coded:
            return coded
    if bordered and (number.strip() or name.strip()):
        parts = []
        if number.strip():
            parts.append(f"Chapter {number.strip()}")
        if name.strip():
            parts.append(name.strip())
        base = " - ".join(parts)
        base = re.sub(r'[\\/:*?"<>|]+', "", base)
        base = re.sub(r"\s+", " ", base).strip()
        if base:
            return base + ".pdf"
    return stem + "_fixed.pdf"


def _send_board_zip(pages: list, covers: list, bcfg: dict, dpi: int,
                    orig_name: str, number: str, name: str,
                    medium: str, subject: str):
    """
    "All boards": one PDF per board — identical notes, that board's cover as
    page 1 — delivered as a single zip. The pages are rendered once and shared
    across every PDF; only the cover differs.
    """
    used: set = set()
    tmpdir = tempfile.mkdtemp(dir=WORK_DIR, prefix="zip_")
    buf = io.BytesIO()
    try:
        # PDF pages are already JPEG-compressed inside the PDF, so deflating
        # them again only burns CPU — store them as they are.
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_STORED) as zf:
            for i, (board, cover) in enumerate(covers):
                member = _export_name(orig_name, True, number, name,
                                      board, medium, subject)
                if member in used:          # two boards sharing a code
                    member = f"{os.path.splitext(member)[0]}_{i + 1}.pdf"
                used.add(member)
                imgs = [borders.load_cover(cover, bcfg["template_size"])
                        .convert("RGB")] + pages
                path = os.path.join(tmpdir, f"{i:02d}.pdf")
                imgs[0].save(path, "PDF", resolution=float(dpi),
                             save_all=True, append_images=imgs[1:])
                zf.write(path, arcname=member)
                os.remove(path)             # keep only one PDF on disk at a time
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    buf.seek(0)
    zname = (_coded_name("ALL", medium, subject, number, name, ".zip")
             or os.path.splitext(orig_name)[0] + "_all_boards.zip")
    return send_file(buf, mimetype="application/zip",
                     as_attachment=True, download_name=zname)


@app.route("/api/export", methods=["POST"])
def export():
    """
    Body: {
      job, dpi?, settings: { fid: { pages: [ {angle, rotate, persp, crop, removals} ] } },
      borders?: { on, class, board, stream, number, name, medium, subject }
    }
    Every loaded file's pages go into the SAME document, in rail order, so an
    export is one PDF — except with borders' board set to "__all__", where the
    same document is written once per board (each with its own cover page) and
    the set comes back as a zip.
    """
    data = request.get_json(force=True)
    job_id = data.get("job", "")
    dpi = int(data.get("dpi") or DEFAULT_EXPORT_DPI)
    settings = data.get("settings", {})
    watermark = bool(data.get("watermark", False))
    # Global switch stamps every page; a page whose settings carry a "wmo"
    # override ({on, opacity, scale, rotate, dx, dy}) uses that instead —
    # its own on/off and its own parameters. Legacy clients sent wmScope
    # 'page' + per-page "wm" flags; still honoured below.
    wm_scope = str(data.get("wmScope", "all") or "all")
    wm_opacity = float(data.get("wmOpacity", 1) or 1)
    wm_scale = float(data.get("wmScale", 1) or 1)
    wm_rotate = float(data.get("wmRotate", 0) or 0)
    wm_dx = float(data.get("wmDx", 0) or 0)
    wm_dy = float(data.get("wmDy", 0) or 0)
    wm_center_margins = bool(data.get("wmCenterMargins", False))
    job = _job(job_id)
    palette = job.get("palette")

    # Cache every spelling-fix patch the client sent (each fix embeds its
    # PNG), so the render loop below can resolve them even after a restart.
    for fset0 in settings.values():
        if isinstance(fset0, dict):
            _register_fixes_from_pages(fset0.get("pages") or [])

    # Borders (branded frames + chapter header + optional board/stream cover).
    bd = data.get("borders") or {}
    bd_on = bool(bd.get("on"))
    bcfg = bcover = brenderer = None
    btpls: list = []
    bcovers: list = []          # "All boards": one (board, cover) per output PDF
    bnumber = str(bd.get("number", "") or "")
    bname = str(bd.get("name", "") or "")
    bboard = str(bd.get("board", "") or "")
    bstream = str(bd.get("stream", "") or "")
    bmedium = str(bd.get("medium", "") or "")
    bsubject = str(bd.get("subject", "") or "")
    ball = bool(bd.get("allBoards")) or bboard == ALL_BOARDS
    bzoom = borders._clampf(bd.get("zoom", 1))
    bstretch_w = borders._clampf(bd.get("stretchW", 1))
    bstretch_h = borders._clampf(bd.get("stretchH", 1))
    bfit_mode = str(bd.get("fitMode") or "") \
        or ("width" if bd.get("fitWidth") else "page")
    if bfit_mode not in ("page", "width", "fill"):
        bfit_mode = "page"
    if bd_on:
        bcls = str(bd.get("class", "") or "")
        try:
            bcfg = borders.load_config(bcls)
        except LookupError as e:
            return jsonify({"error": str(e)}), 400
        btpls = borders.list_templates(bcls)
        if not btpls:
            return jsonify({"error": f"no border templates for class {bcls} "
                            f"yet — add PNGs to borders/{bcls}/templates/"}), 400
        if ball:
            # One PDF per board that has a cover for the picked stream
            # (streamless classes match their board-only covers).
            bcovers = borders.boards_with_covers(bcls, bstream)
            if not bcovers:
                return jsonify({"error": f"no {bcls} cover pages for "
                                + (f"stream {bstream}" if bstream
                                   else "the boards — pick a stream")}), 400
        elif bboard:
            # Streamless classes (10th) store covers under the board alone;
            # a board picked without a stream where streams DO exist simply
            # exports without a cover, as before.
            bcover = borders.find_cover(bcls, bboard, bstream)
            if bcover is None and bstream:
                return jsonify({"error": f"no cover page for {bboard} / {bstream}"}), 400
        brenderer = borders.HeaderRenderer(bcfg, bnumber, bname, bmedium)

    # Every loaded PDF exports into ONE document, in rail order — an export is
    # always a single PDF, never a zip of separate ones.
    out_images = []

    # Merged-page overlays reference source pages by fid+page; they may live in
    # any loaded PDF, so keep one lazily-opened doc per fid for the whole export.
    fid_paths = {f["fid"]: f["path"] for f in job["files"]}
    src_docs: dict = {}

    def _render_overlay_src(ov):
        fid = str(ov.get("fid", "") or "")
        path = fid_paths.get(fid)
        if path is None:
            return None
        d = src_docs.get(fid)
        if d is None:
            d = src_docs[fid] = fitz.open(path)
        pno = int(ov.get("page", 0) or 0)
        if not 0 <= pno < d.page_count:
            return None
        return imaging.render_page(d, pno, dpi)

    # One headless browser serves the chapter header (no-op when off). The
    # frame never changes size, so a single overlay serves every page.
    with (brenderer if brenderer is not None else contextlib.nullcontext()):
        bheader = brenderer.render(bcfg["template_size"][0], 1.0, 1.0) \
            if bd_on else None
        for f in job["files"]:
            fset = settings.get(f["fid"], {})
            page_settings = fset.get("pages", [])
            doc = fitz.open(f["path"])
            images = []
            tpl_i = 0                       # frame designs cycle per file
            # Pages render in the order the editor sends them (reordering);
            # each entry's "src" is the page's index inside the working PDF.
            if page_settings:
                ordered = [(int(ps.get("src", idx)), ps)
                           for idx, ps in enumerate(page_settings)]
            else:
                ordered = [(i, {}) for i in range(doc.page_count)]
            for i, ps in ordered:
                if not 0 <= i < doc.page_count:
                    continue
                if ps.get("deleted"):
                    continue          # page was deleted in the editor — skip it
                angle = float(ps.get("angle", f["pages"][i]["angle"]))
                rot = float(ps.get("rotate", 0) or 0)
                persp = ps.get("persp")
                crop = ps.get("crop", f["pages"][i]["crop"])
                removals = ps.get("removals") if "removals" in ps else f["pages"][i].get("removals")
                color = ps.get("color") or imaging.DEFAULT_COLOR
                # Content pulled from other pages is part of the page too: where
                # it sits past the margins the sheet grows to keep it instead of
                # clipping it. Everything downstream measures against that grown
                # box — only the watermark still anchors to the real margins.
                ecrop = imaging.expanded_crop(crop, ps.get("overlays"))
                hi = imaging.render_page(doc, i, dpi)
                processed = imaging.process_page(hi, angle, ecrop, color, palette,
                                                 removals, rot, persp,
                                                 ps.get("fixes"))
                if ps.get("overlays"):
                    processed = imaging.paste_overlays(
                        processed, ps["overlays"], ecrop, palette,
                        _render_overlay_src)
                if ps.get("shapes"):
                    processed = imaging.draw_shapes(processed, ps["shapes"], ecrop)
                wov = ps.get("wmo") or {}

                def _wp(key, default):
                    try:
                        return float(wov[key])
                    except (KeyError, TypeError, ValueError):
                        return default

                if wov:
                    stamp = bool(wov.get("on"))
                else:
                    stamp = watermark and (wm_scope != "page" or ps.get("wm"))
                if stamp:
                    sheet, centre = imaging.watermark_geometry(
                        processed.size, ecrop, wm_center_margins, cropped=True,
                        margin_crop=crop)
                    processed = imaging.apply_watermark(
                        processed,
                        _wp("opacity", wm_opacity), _wp("scale", wm_scale),
                        _wp("rotate", wm_rotate), _wp("dx", wm_dx),
                        _wp("dy", wm_dy), sheet, centre,
                        align_ink=wm_center_margins)
                if bd_on:
                    tpl = borders.load_template(btpls[tpl_i % len(btpls)])
                    tpl_i += 1
                    # per-page fit (falls back to the job-level values)
                    pbf = ps.get("bfit") or {}
                    pmode = str(pbf.get("mode") or bfit_mode)
                    if pmode not in ("page", "width", "fill"):
                        pmode = "page"
                    processed = borders.compose_bordered(
                        processed, tpl, bcfg, bheader,
                        zoom=borders._clampf(pbf.get("zoom", bzoom)),
                        stretch_w=borders._clampf(pbf.get("stretchW", bstretch_w)),
                        stretch_h=borders._clampf(pbf.get("stretchH", bstretch_h)),
                        fit_mode=pmode,
                        align_x=borders._clampa(pbf.get("ox", 0)),
                        align_y=borders._clampa(pbf.get("oy", 0)))
                images.append(processed.convert("RGB"))
            doc.close()

            if not images:
                continue              # every page of this PDF was deleted
            out_images.extend(images)

    for d in src_docs.values():
        d.close()

    if not out_images:
        return jsonify({"error": "every page is deleted — nothing to export"}), 400

    orig_name = job["files"][0]["name"]

    # "All boards": the notes are done — write them once per board, each with
    # that board's cover in front, and hand back the zip.
    if bd_on and bcovers:
        return _send_board_zip(out_images, bcovers, bcfg, dpi, orig_name,
                               bnumber, bname, bmedium, bsubject)

    # The cover belongs at the very front of the one document, not per file.
    if bd_on and bcover is not None:
        out_images.insert(0, borders.load_cover(
            bcover, bcfg["template_size"]).convert("RGB"))

    out_name = _export_name(orig_name, bd_on, bnumber, bname,
                            bboard, bmedium, bsubject)
    buf = io.BytesIO()
    out_images[0].save(buf, "PDF", resolution=float(dpi),
                       save_all=True, append_images=out_images[1:])
    buf.seek(0)
    return send_file(buf, mimetype="application/pdf",
                     as_attachment=True, download_name=out_name)


# ---------------------------------------------------------------------------
# Drafts (persistent history of exported/edited sessions)
# ---------------------------------------------------------------------------

def _draft_dir(did: str, must_exist: bool = True) -> str:
    if not _DRAFT_ID.match(did or ""):
        abort(400, "bad draft id")
    path = os.path.join(DRAFTS_DIR, did)
    if must_exist and not os.path.isfile(os.path.join(path, "draft.json")):
        abort(404, "no such draft")
    return path


def _read_draft_meta(did: str) -> dict:
    with open(os.path.join(_draft_dir(did), "draft.json"), encoding="utf-8") as fh:
        return json.load(fh)


@app.route("/api/drafts")
def drafts_list():
    """All saved drafts, newest first (metadata only, no state payload)."""
    items = []
    if os.path.isdir(DRAFTS_DIR):
        for name in os.listdir(DRAFTS_DIR):
            jpath = os.path.join(DRAFTS_DIR, name, "draft.json")
            if not os.path.isfile(jpath):
                continue
            try:
                with open(jpath, encoding="utf-8") as fh:
                    meta = json.load(fh)
            except (OSError, ValueError):
                continue
            items.append({
                "id": meta.get("id", name),
                "name": meta.get("name", "Untitled draft"),
                "created": meta.get("created", 0),
                "updated": meta.get("updated", 0),
                "files": [{"name": f.get("name"), "npages": f.get("npages")}
                          for f in meta.get("files", [])],
                "npages": meta.get("npages", 0),
                "exports": meta.get("exports", 0),
            })
    items.sort(key=lambda m: m.get("updated", 0), reverse=True)
    return jsonify({"drafts": items})


@app.route("/api/drafts/save", methods=["POST"])
def drafts_save():
    """
    Snapshot the current job into a draft: copies each working PDF (with any
    appended PYQs baked in) plus the client's full edit state.
    Body: { job, draft?, name?, state, exported? }.  Passing an existing
    draft id updates it in place, so re-exports don't pile up duplicates.
    """
    data = request.get_json(force=True)
    job = _job(data.get("job", ""))

    did = str(data.get("draft") or "")
    existing = None
    if did:
        if not _DRAFT_ID.match(did):
            abort(400, "bad draft id")
        # A stale id (draft deleted meanwhile) just re-creates it fresh.
        jpath = os.path.join(DRAFTS_DIR, did, "draft.json")
        if os.path.isfile(jpath):
            with open(jpath, encoding="utf-8") as fh:
                existing = json.load(fh)
    else:
        did = uuid.uuid4().hex[:12]

    ddir = os.path.join(DRAFTS_DIR, did)
    fdir = os.path.join(ddir, "files")
    os.makedirs(fdir, exist_ok=True)

    files_meta = []
    for i, f in enumerate(job["files"]):
        stored = f"{i:02d}.pdf"
        shutil.copyfile(f["path"], os.path.join(fdir, stored))
        files_meta.append({"stored": stored, "name": f["name"],
                           "npages": f["npages"]})
    # An update with fewer files than before leaves stale PDFs — drop them.
    keep = {fm["stored"] for fm in files_meta}
    for name in os.listdir(fdir):
        if name.endswith(".pdf") and name not in keep:
            os.remove(os.path.join(fdir, name))

    # First-page thumbnail for the history list (raw page — recognisable
    # enough, and it costs one low-DPI render).
    try:
        doc = fitz.open(job["files"][0]["path"])
        thumb = imaging.render_page(doc, 0, 40)
        doc.close()
        thumb.save(os.path.join(ddir, "thumb.png"))
    except Exception:
        pass

    now = time.time()
    meta = {
        "id": did,
        "name": str(data.get("name") or "").strip() or "Untitled draft",
        "created": existing["created"] if existing else now,
        "updated": now,
        "exports": (existing.get("exports", 0) if existing else 0)
                   + (1 if data.get("exported") else 0),
        "files": files_meta,
        "npages": sum(fm["npages"] for fm in files_meta),
        "state": data.get("state") or {},
    }
    tmp = os.path.join(ddir, "draft.json.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(meta, fh)
    os.replace(tmp, os.path.join(ddir, "draft.json"))
    return jsonify({"draft": did, "name": meta["name"], "updated": now})


@app.route("/api/drafts/<did>/thumb")
def drafts_thumb(did: str):
    path = os.path.join(_draft_dir(did), "thumb.png")
    if not os.path.isfile(path):
        abort(404, "no thumbnail")
    return send_file(path, mimetype="image/png")


@app.route("/api/drafts/<did>/open", methods=["POST"])
def drafts_open(did: str):
    """
    Rebuild a live editing job from a saved draft: the stored PDFs go through
    the same render/deskew/margin pipeline as a fresh upload (so previews and
    the "Auto" reset baselines exist), and the saved edit state rides along
    for the client to lay on top.
    """
    meta = _read_draft_meta(did)
    ddir = _draft_dir(did)

    job_id = uuid.uuid4().hex[:12]
    job_dir = os.path.join(WORK_DIR, job_id)
    os.makedirs(job_dir, exist_ok=True)

    copied = []
    for fm in meta.get("files", []):
        src = os.path.join(ddir, "files", fm["stored"])
        if not os.path.isfile(src):
            continue
        fid = uuid.uuid4().hex[:8]
        path = os.path.join(job_dir, f"{fid}.pdf")
        # Work on a copy — later edits/PYQ appends must never touch the draft.
        shutil.copyfile(src, path)
        copied.append({"fid": fid, "name": fm["name"], "path": path})

    token = (request.args.get("ptoken") or "").strip()
    with _progress(token, 0, "Reopening draft…") as prog:
        if prog is not None:
            prog["total"] = sum(_page_count(c["path"]) for c in copied)
        files = []
        for c in copied:
            pages = _analyse_pages(job_id, c["fid"], c["path"],
                                   prog=prog, label=c["name"])
            files.append({**c, "npages": len(pages), "pages": pages})

    if not files:
        return jsonify({"error": "draft has no PDFs on disk"}), 404

    JOBS[job_id] = {"files": files, "dir": job_dir}
    state = meta.get("state") or {}
    if state.get("palette"):
        JOBS[job_id]["palette"] = state["palette"]
    # Spelling-fix patches ride in the saved state as base64 PNGs; cache them
    # so previews can resolve them by id straight away.
    for sf in state.get("files") or []:
        if isinstance(sf, dict):
            _register_fixes_from_pages(sf.get("pages") or [])

    payload_files = [{
        "fid": f["fid"], "name": f["name"], "npages": f["npages"],
        "pages": f["pages"],
    } for f in files]
    return jsonify({"job": job_id, "files": payload_files,
                    "draft": did, "name": meta.get("name"), "state": state})


@app.route("/api/drafts/<did>", methods=["DELETE"])
def drafts_delete(did: str):
    shutil.rmtree(_draft_dir(did), ignore_errors=True)
    return jsonify({"ok": True})


def _pyqs_path(*parts) -> str:
    """Resolve a folder inside PYQS_DIR from validated path segments."""
    for p in parts:
        if not p or not _SAFE_SEG.match(p):
            abort(400, "bad PYQs path segment")
    path = os.path.join(PYQS_DIR, *parts)
    if not os.path.isdir(path):
        abort(404, "no such PYQs folder")
    return path


@app.route("/api/pyqs/options")
def pyqs_options():
    """
    List the next level of the PYQs tree. Pass none/some of board, medium,
    subject, chapter; returns subfolders (dirs) and PDFs at that level.
    """
    parts = []
    for key in ("board", "medium", "subject", "chapter"):
        val = request.args.get(key, "")
        if not val:
            break
        parts.append(val)
    path = _pyqs_path(*parts) if parts else PYQS_DIR
    if not os.path.isdir(path):
        abort(404, "PYQs folder missing — create it next to server.py")
    dirs, pdfs = [], []
    for name in os.listdir(path):
        if name.startswith("."):
            continue
        if os.path.isdir(os.path.join(path, name)):
            dirs.append(name)
        elif name.lower().endswith(".pdf"):
            pdfs.append(name)
    dirs.sort(key=lambda n: (0, int(n)) if n.isdigit() else (1, n))
    pdfs.sort()
    return jsonify({"dirs": dirs, "pdfs": pdfs})


@app.route("/api/pyqs/append", methods=["POST"])
def pyqs_append():
    """
    Append every PDF in PYQs/<board>/<medium>/<subject>/<chapter>/ to the end
    of one loaded file. The new pages go through the same auto-deskew and
    auto-margin pipeline as uploaded pages, so they are editable like any
    other page and export as part of the same PDF.
    """
    data = request.get_json(force=True)
    job_id = data.get("job", "")
    job = _job(job_id)
    f = _find_file(job, data.get("fid", ""))
    folder = _pyqs_path(str(data.get("board", "")), str(data.get("medium", "")),
                        str(data.get("subject", "")), str(data.get("chapter", "")))

    pdf_names = sorted(n for n in os.listdir(folder)
                       if n.lower().endswith(".pdf") and not n.startswith("."))
    if not pdf_names:
        return jsonify({"error": "no PYQ PDFs uploaded in that chapter folder yet"}), 404

    doc = fitz.open(f["path"])
    start = doc.page_count
    for name in pdf_names:
        src = fitz.open(os.path.join(folder, name))
        doc.insert_pdf(src)
        src.close()
    added = doc.page_count - start
    tmp = f["path"] + ".tmp"
    doc.save(tmp)
    doc.close()
    os.replace(tmp, f["path"])

    token = str(data.get("ptoken") or "").strip()
    with _progress(token, added, f["name"]) as prog:
        new_pages = _analyse_pages(job_id, f["fid"], f["path"], start,
                                   prog=prog, label=f["name"])
    f["pages"].extend(new_pages)
    f["npages"] = len(f["pages"])

    return jsonify({"fid": f["fid"], "start": start, "npages": f["npages"],
                    "pages": new_pages, "sources": pdf_names})


# ---------------------------------------------------------------------------
# Borders (branded frames integrated from arivihan-notes-composer)
# ---------------------------------------------------------------------------

@app.route("/fonts/<name>")
def font_file(name: str):
    """Serve the Urbanist variable font to the editor's live border preview."""
    if not re.match(r"^[A-Za-z0-9._-]+$", name) or name.startswith("."):
        abort(400, "bad font name")
    path = os.path.join(FONTS_DIR, name)
    if not os.path.isfile(path):
        abort(404, "no such font")
    resp = send_file(path)
    resp.headers["Cache-Control"] = "public, max-age=86400"
    return resp


@app.route("/api/borders/options")
def borders_options():
    """Classes, boards/streams and frame geometry for the Borders tab."""
    data = borders.options()
    code = [os.path.abspath(__file__), borders.__file__, imaging.__file__]
    try:
        newest = max(os.path.getmtime(f) for f in code if f and os.path.isfile(f))
        data["stale_server"] = newest > _PROCESS_START + 1
    except OSError:
        data["stale_server"] = False
    return jsonify(data)


@app.route("/api/borders/template")
def borders_template():
    """
    Downscaled PNG of one frame design, for the live in-editor overlay.
    Params: class (e.g. 12th), i (page's template index), w (pixel width).
    """
    cls = request.args.get("class", "")
    idx = int(request.args.get("i", "0") or 0)
    width = int(request.args.get("w", "1000") or 1000)
    try:
        data = borders.template_preview_png(cls, idx, width)
    except LookupError as e:
        abort(404, str(e))
    resp = Response(data, mimetype="image/png")
    resp.headers["Cache-Control"] = "public, max-age=86400"
    return resp


if __name__ == "__main__":
    import webbrowser
    import threading

    port = int(os.environ.get("PORT", "5001"))  # 5000 is taken by macOS AirPlay
    url = f"http://127.0.0.1:{port}"
    threading.Timer(1.0, lambda: webbrowser.open(url)).start()
    print(f"\n  Notes Deskewer running at {url}\n  (Ctrl-C to stop)\n")
    app.run(host="127.0.0.1", port=port, debug=False, threaded=True)
